version: '3.7'
services:
  gerocuidado-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gerocuidado-front
    ports:
      - '8081:8081'
      - '19001:19001'
      - '19002:19002'
      - '19006:19006'
    volumes:
      - .:/opt/my-app
      - /opt/my-app/node_modules
    env_file:  # Refere-se ao arquivo .env.development
      - .env.development
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=192.168.0.15
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.15
    networks:
      - gerocuidado-apis-net  # Mapeia explicitamente para a rede externa

networks:
  gerocuidado-apis-net:
    external: true  # Declara que a rede jรก existe
